from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage
from pathlib import Path
from typing import Any

from .data import AUTOMATION_ROOT, WORKSPACE_ROOT
from .supabase_sync import load_env_file


def send_or_queue_result_email(to_email: str, case_output: dict[str, Any]) -> dict[str, Any]:
    message = build_result_message(to_email, case_output)
    config = smtp_config()
    if not config:
        return write_outbox_message(message, case_output["case_id"])

    if config["use_tls"]:
        with smtplib.SMTP(config["host"], config["port"], timeout=20) as smtp:
            smtp.starttls()
            smtp.login(config["username"], config["password"])
            smtp.send_message(message)
    else:
        with smtplib.SMTP_SSL(config["host"], config["port"], timeout=20) as smtp:
            smtp.login(config["username"], config["password"])
            smtp.send_message(message)
    return {"status": "sent", "to": to_email}


def smtp_config() -> dict[str, Any] | None:
    load_env_file(WORKSPACE_ROOT / ".env")
    load_env_file(AUTOMATION_ROOT / ".env")
    host = os.environ.get("SMTP_HOST")
    username = os.environ.get("SMTP_USERNAME")
    password = os.environ.get("SMTP_PASSWORD")
    from_email = os.environ.get("SMTP_FROM") or username
    if not host or not username or not password or not from_email:
        return None
    return {
        "host": host,
        "port": int(os.environ.get("SMTP_PORT", "587")),
        "username": username,
        "password": password,
        "from_email": from_email,
        "use_tls": os.environ.get("SMTP_USE_TLS", "true").lower() != "false",
    }


def build_result_message(to_email: str, case_output: dict[str, Any]) -> EmailMessage:
    analysis = case_output["analysis"]
    service_fit = analysis["service_fit"]
    pricing = analysis["pricing_recommendation"]
    balanced = next(
        (scenario for scenario in pricing.get("scenarios", []) if scenario["id"] == pricing.get("recommended_scenario_id")),
        None,
    )
    message = EmailMessage()
    config = smtp_config() or {"from_email": "amazon-copilot-demo@localhost"}
    message["To"] = to_email
    message["From"] = config["from_email"]
    message["Subject"] = f"Amazon Shipping review complete: {analysis['company']}"
    lines = [
        f"Review complete for {analysis['company']}",
        "",
        f"Recommendation: {analysis['recommendation']}",
        f"Opportunity score: {analysis['opportunity_score']['score']}/100",
        f"Win probability: {round(analysis['win_probability_score']['probability'] * 100)}%",
        f"Risk level: {analysis['risk_assessment']['level']}",
        f"Serviceable annual volume: {service_fit['serviceable_annual_volume']:,}",
        f"Serviceable daily volume: {service_fit['serviceable_daily_volume']:,}",
        f"Export status: {analysis['export_status'].replace('_', ' ')}",
    ]
    if balanced:
        lines.extend([
            "",
            f"Balanced price: EUR {balanced['price_per_parcel_eur']:.2f} per parcel",
            f"Balanced margin: {round(balanced['target_margin'] * 100)}%",
        ])
    lines.extend([
        "",
        "Required follow-up actions:",
        *[f"- {item['owner']}: {item['question']}" for item in analysis["required_follow_up_actions"]],
        "",
        "Open the local dashboard:",
        f"http://localhost:8000/dashboard.html?case={case_output['case_id']}",
        "",
        "This message was generated by the local Amazon Shipping Opportunity Copilot MVP.",
    ])
    message.set_content("\n".join(lines))
    return message


def write_outbox_message(message: EmailMessage, case_id: str) -> dict[str, Any]:
    outbox_override = os.environ.get("AMAZON_COPILOT_OUTBOX_DIR")
    outbox = Path(outbox_override) if outbox_override else AUTOMATION_ROOT / "outbox"
    outbox.mkdir(parents=True, exist_ok=True)
    path = outbox / f"{case_id}.eml"
    path.write_text(message.as_string(), encoding="utf-8")
    try:
        display_path = str(path.relative_to(WORKSPACE_ROOT))
    except ValueError:
        display_path = str(path)
    return {
        "status": "queued",
        "reason": "SMTP settings are not configured in .env.",
        "path": display_path,
    }
